# Generated by Django 4.0.3 on 2022-04-23 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webexample', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Pets',
        ),
        migrations.AlterModelOptions(
            name='pets',
            options={'verbose_name': 'Питомец', 'verbose_name_plural': 'Питомцы'},
        ),
        migrations.RenameField(
            model_name='pets',
            old_name='task',
            new_name='pet',
        ),
    ]
