# Generated by Django 4.0.3 on 2022-04-23 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webexample', '0002_rename_task_pets_alter_pets_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pets',
            name='image',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('Pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Фото', to='webexample.pets')),
            ],
        ),
    ]
