# Generated by Django 4.0.3 on 2022-04-23 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webexample', '0003_remove_pets_image_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
    ]
