# Generated by Django 4.0.3 on 2022-04-23 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webexample', '0004_alter_photo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='Pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='webexample.pets'),
        ),
    ]
