# Generated by Django 4.0.3 on 2022-04-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webexample', '0005_alter_photo_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
